"""Block detection package — contract boundary and pipeline skeleton."""

from .detection_contract import (
    BLOCK_ID_TO_LABEL,
    SAMPLE_LOW_CONFIDENCE,
    SAMPLE_NO_DETECTION,
    SAMPLE_OUTPUTS_JSON,
    SAMPLE_SUCCESS_BLOCK_1,
    BlockID,
    BlockLabel,
    BoundingBoxPx,
    CornersPx,
    DebugInfo,
    DetectionContractError,
    DetectionResult,
    DetectionStatus,
    PickupPose,
    PointPx,
    make_multiple_candidates_result,
    make_no_detection_result,
    result_to_dict,
    result_to_json,
    validate_detection_result,
)
from .camera import (
    CameraSettings,
    CaptureFrame,
    FrameSource,
    ImageSequenceFrameSource,
    PiCamera2FrameSource,
    UsbVideoCaptureFrameSource,
    create_frame_source,
    load_camera_settings,
)
from .debug import DebugFrameWriter, DebugSettings
from .detector import DetectorSettings, SquareCandidate, find_square_candidates
from .calibration import CalibrationSettings, load_calibration_settings, pixel_to_pickup_pose
from .classifier import (
    ClassificationResult,
    ClassifierSettings,
    StubFaceClassifier,
    classify_face,
    create_classifier,
)
from .pipeline import PipelineSettings, detect_block
from .preprocess import PreprocessResult, PreprocessSettings, preprocess_bgr
from .geometry import (
    FaceGeometry,
    GeometrySettings,
    compute_center_and_angle,
    geometry_from_candidate,
    order_corners_tl_tr_br_bl,
    warp_face_bgr,
)
from .vision import (
    FrameCandidates,
    VisionSettings,
    draw_candidate_overlay,
    find_square_candidates_from_frame,
)

__version__ = "0.1.0"

__all__ = [
    "BLOCK_ID_TO_LABEL",
    "BlockID",
    "BlockLabel",
    "BoundingBoxPx",
    "CornersPx",
    "DebugInfo",
    "DetectionContractError",
    "DetectionResult",
    "DetectionStatus",
    "PickupPose",
    "PointPx",
    "SAMPLE_LOW_CONFIDENCE",
    "SAMPLE_NO_DETECTION",
    "SAMPLE_OUTPUTS_JSON",
    "SAMPLE_SUCCESS_BLOCK_1",
    "CalibrationSettings",
    "ClassificationResult",
    "ClassifierSettings",
    "CameraSettings",
    "CaptureFrame",
    "DebugFrameWriter",
    "DebugSettings",
    "DetectorSettings",
    "FaceGeometry",
    "FrameCandidates",
    "FrameSource",
    "GeometrySettings",
    "ImageSequenceFrameSource",
    "PiCamera2FrameSource",
    "UsbVideoCaptureFrameSource",
    "__version__",
    "SquareCandidate",
    "compute_center_and_angle",
    "StubFaceClassifier",
    "classify_face",
    "create_classifier",
    "create_frame_source",
    "geometry_from_candidate",
    "detect_block",
    "draw_candidate_overlay",
    "find_square_candidates",
    "find_square_candidates_from_frame",
    "load_calibration_settings",
    "load_camera_settings",
    "pixel_to_pickup_pose",
    "PipelineSettings",
    "order_corners_tl_tr_br_bl",
    "preprocess_bgr",
    "warp_face_bgr",
    "PreprocessResult",
    "PreprocessSettings",
    "make_multiple_candidates_result",
    "make_no_detection_result",
    "result_to_dict",
    "result_to_json",
    "validate_detection_result",
    "VisionSettings",
]
