from __future__ import annotations

from pathlib import Path

_PKG_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _PKG_DIR.parent.parent

SOURCE = "images"
CAMERA_INDEX = 0
FRAME_WIDTH = 1280
FRAME_HEIGHT = 720

IMAGE_DIR = str(_PKG_DIR / "block_dataset")
IMAGE_PAUSE_MS = 0

CANNY_LOW = 40
CANNY_HIGH = 140
CANNY_APERTURE = 3

MIN_CONTOUR_AREA = 2500.0
POLYGON_EPSILON_RATIO = 0.02
CONVEXITY_TOLERANCE = 0.28
DETECTION_SCORE_MIN = 0.42

HOUGH_RHO = 1
HOUGH_THETA_DEG = 1.0
HOUGH_THRESHOLD = 50
HOUGH_MIN_LINE_LEN = 30
HOUGH_MAX_LINE_GAP = 16
USE_LSD = False

CLAHE_CLIP = 2.0
CLAHE_TILE = (8, 8)
GAUSSIAN_KERNEL = (5, 5)
RESIZE_WIDTH = 0

EMA_ALPHA = 0.35
MAX_POINT_JUMP = 120.0
LOST_HOLD_FRAMES = 4

MIN_FACE_AREA = 150.0
MAX_BLOCKS = 8
MIN_BLOCK_CENTER_DIST = 50.0

BLOCK_MODE = 3
ROI_PALLET_FRAC = 0.78
ROI_RIGHT_TRIM_FRAC = 0.22

# Standard trapezoid hex (A–F) from ROI + Hough angles
HEX_SPLIT_FRAC = 0.48  # B on AC, E on FD — front / (front+right) width ratio
HEX_INSET_X_FRAC = 0.06
HEX_INSET_Y_FRAC = 0.08

SCORE_AREA_RATIO_MIN = 0.12
SCORE_HEX_AREA_MIN = 3500.0
SCORE_WEIGHT_AREA = 0.35
SCORE_WEIGHT_EDGE = 0.45
SCORE_WEIGHT_TOPO = 0.20
USE_CONTOUR_FALLBACK = False

USE_YOLO_ROI = True
YOLO_MODEL_PATH = str(_REPO_ROOT / "models" / "rbs-final.pt")
YOLO_CONF = 0.25
YOLO_IOU = 0.45
YOLO_PAD_FRAC = 0.08
YOLO_DEVICE = None

DEBUG_EDGES = False
DEBUG_LINES = False
DEBUG_CONTOUR = False
DEBUG_YOLO = False

WINDOW_NAME = "block_detection_v2"
