"""Configuration — paths, defaults, schema, and store."""

from block_detected.config.defaults import (
    BUTTON_HEIGHT,
    BUTTON_MARGIN,
    BUTTON_PAD_X,
    CAMERA_HEIGHT,
    CAMERA_INDEX,
    CAMERA_WIDTH,
    CONF_MAX,
    CONF_MIN,
    CONF_STEP,
    DEFAULT_CONF,
    DEFAULT_MODEL_NAME,
    EVAL_CONF,
    KEY_ARROW_DOWN,
    KEY_ARROW_UP,
    MAX_CAMERA_INDEX,
    WINDOW_NAME,
)
from block_detected.config.paths import MODELS_DIR, PACKAGE_ROOT, PROJECT_ROOT
from block_detected.config.schema import (
    AppConfig,
    CameraConfig,
    ClassicalPipelineConfig,
    InferenceConfig,
    PreprocessConfig,
    RESTART_CAMERA_KEYS,
    RESTART_DETECTOR_KEYS,
    StabilityConfig,
    UiDebugConfig,
)
from block_detected.config.store import (
    DEFAULT_CONFIG_PATH,
    load_config,
    save_config,
    validate_config,
)

__all__ = [
    "PROJECT_ROOT",
    "PACKAGE_ROOT",
    "MODELS_DIR",
    "DEFAULT_CONFIG_PATH",
    "DEFAULT_MODEL_NAME",
    "CAMERA_INDEX",
    "MAX_CAMERA_INDEX",
    "CAMERA_WIDTH",
    "CAMERA_HEIGHT",
    "WINDOW_NAME",
    "CONF_MIN",
    "CONF_MAX",
    "CONF_STEP",
    "DEFAULT_CONF",
    "EVAL_CONF",
    "BUTTON_MARGIN",
    "BUTTON_HEIGHT",
    "BUTTON_PAD_X",
    "KEY_ARROW_UP",
    "KEY_ARROW_DOWN",
    "AppConfig",
    "CameraConfig",
    "InferenceConfig",
    "PreprocessConfig",
    "ClassicalPipelineConfig",
    "StabilityConfig",
    "UiDebugConfig",
    "RESTART_CAMERA_KEYS",
    "RESTART_DETECTOR_KEYS",
    "load_config",
    "save_config",
    "validate_config",
]
